name: Telegram notification

on:
  push:
    branches:
      - master
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  telegram_notification:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}